### ISSUE TITLE
Pre-trained model and the data

### ISSUE THREAD

**Issue by dopc** [Speaker-Identification/You-Only-Speak-Once#1]
Hey,
Thx for your great job and sharing it.

Can I please have the pre-trained models, the data and info for how to use them for my purpose?
I do not have enough hardware to train a model like this.

**Comment by vivekkr12** [comment]
Take a look at [demo](https://github.com/Speaker-Identification/You-Only-Speak-Once/tree/master/fbank_net/demo) and [demo section](https://github.com/Speaker-Identification/You-Only-Speak-Once#demo) in readme.

The pre-trained weights are [here](https://github.com/Speaker-Identification/You-Only-Speak-Once/tree/master/fbank_net/weights)

**Comment by dopc** [comment]
thank you so much
